version: '3.8'

services:
  main:
    build: ./backend/main
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/main/:/app/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - TZ=${TIMEZONE}
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${TIMEZONE}


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./server/nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main
    environment:
      - TZ=${TIMEZONE}

volumes:
  db:
